
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>

development:
  <<: *default
  username: doadmin
  password: AVNS_27eJ-pxOs62WfQ9kk3r
  host: db-postgresql-nyc3-89877-do-user-15310791-0.c.db.ondigitalocean.com
  port: 25060
  database: defaultdb
  sslmode: require

production:
  <<: *default
  username: doadmin
  password: AVNS_27eJ-pxOs62WfQ9kk3r
  host: db-postgresql-nyc3-89877-do-user-15310791-0.c.db.ondigitalocean.com
  port: 25060
  database: defaultdb
  sslmode: require

  