
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: Oficina
  username: postgres
  password: root 
  host: localhost

development:
  <<: *default
  database: Oficina/development

test:
  <<: *default
  database: Oficina/test

production:
  <<: *default
  database: Oficina/production
